-- Migration 009: Add Body Battery and Daily Activity tables

-- 1. Body Battery Table
CREATE TABLE IF NOT EXISTS body_battery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL, -- Or INT if using a custom user table, checking prev migrations implies INT for user_id in public schema but let's check supabase_client. It uses 'users' table which has 'id'. Wait, previous migrations used 'users' table which likely uses SERIAL/INT not UUID based on python code `user_id: int`. Let's check `007`.
    date DATE NOT NULL,
    highest INT,
    lowest INT,
    charged INT,
    drained INT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, date)
);

-- Check user_id type in previous tables (from 007 and supabase_client)
-- In supabase_client.py: user_id is int.
-- In 007: s.user_id = hr.user_id. References public.users(id).
-- Let's assume standard INT for now based on python type hinting `user_id: int`.

-- Re-doing table definition with INT for user_id to match existing pattern
DROP TABLE IF EXISTS body_battery;
CREATE TABLE IF NOT EXISTS body_battery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    highest INT,
    lowest INT,
    charged INT,
    drained INT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, date)
);

-- 2. Daily Activity Table (Steps, Intensity Minutes)
CREATE TABLE IF NOT EXISTS daily_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    steps INT,
    step_goal INT,
    floors_climbed INT,
    distance_meters FLOAT,
    moderate_intensity_minutes INT,
    vigorous_intensity_minutes INT,
    intensity_minutes_goal INT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, date)
);

-- 3. Enable RLS (Row Level Security) - Optional but good practice
ALTER TABLE body_battery ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_activity ENABLE ROW LEVEL SECURITY;

-- 4. Create policies (assuming public access for service role for now, or match existing pattern)
-- Existing pattern seems to treat Supabase as backend-as-a-service with service role key, so policies might be permissive or handled by application logic.
-- I'll skip complex RLS policies for now to match simplicity of existing setup unless requested.

-- 5. Add useful comments
COMMENT ON TABLE body_battery IS 'Garmin Body Battery energy monitoring';
COMMENT ON TABLE daily_activity IS 'Daily activity stats like steps and intensity minutes';
