-- Migration 010: Add conversation history

CREATE TABLE IF NOT EXISTS conversation_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    role VARCHAR(20) NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for faster retrieval by user and time
CREATE INDEX IF NOT EXISTS idx_conversation_history_user_date ON conversation_history(user_id, created_at DESC);

COMMENT ON TABLE conversation_history IS 'Stores chat history for context-aware AI responses';
